### ISSUE TITLE
If tab is unfocused it will affect player movement

### ISSUE THREAD

**Issue by Its-Kenta** [jstewart7/mmo#28]
If player minimised, switched tab or opens a desktop app and returns back to the tab players movement and position becomes unstable and prevents the player to move to different directions and snaps them back to their original position.

Persistent movement will attempt to move player in desired direction but will result in map tearing.
See video -> https://discord.com/channels/969627014283821056/969627014283821061/1040390675201536020

**Comment by unitoftime** [comment]
This probably has something to do with: https://github.com/unitoftime/mmo/issues/25

I'm not really sure how to fix yet. I might need a wasm callback, when the window goes back into focus I clear some botched state and return the game. Or If we lose focus we just log the player out then log them back in. My initial thoughts from looking at the vid are that the client replay buffer is getting into some weird state because of the connection loss and reconnect. Will have to debug more.
