### ISSUE TITLE
Issues with big displays

### ISSUE THREAD

**Issue by unitoftime** [jstewart7/mmo#32]
mac m1 issues: apple xdr display. 6K display

"3440x1440 monitor it balck screens if full screen"

Kavin Aravind
​wasm_exec.js:349 WebGL: INVALID_OPERATION: texImage2D: ArrayBufferView not big enough for request

Kavin Aravind
​[.WebGL-0x118059cee00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete: Attachment has zero size.

Kavin Aravind
​[.WebGL-0x118059cee00] GL_INVALID_FRAMEBUFFER_OPERATION: Draw framebuffer is incomplete

Kavin Aravind
​WebGL: too many errors, no more errors will be reported to the console for this context.

**Comment by unitoftime** [comment]
"16.2-inch (diagonal) Liquid Retina XDR display;1 3456-by-2234 nativeresolution at 254 pixels per inch"

**Comment by Its-Kenta** [comment]
Same issue at 4k, see attached.
[console-export-2023-1-4_14-42-26.txt](https://github.com/unitoftime/mmo/files/10345003/console-export-2023-1-4_14-42-26.txt)

2K is fine.

**Comment by unitoftime** [comment]
Oh nice that's good info to have. What OS were you on?

**Comment by Its-Kenta** [comment]
> Oh nice that's good info to have. What OS were you on?

Silly question, Linux of course. The only OS UnitOfCo allows.

**Comment by Its-Kenta** [comment]
Turns out the game runs fine on macOS, but on high res size the frame buffer as you said is probably too small (16MB). When you resize the browser video to a smaller resolution we get output.

Tested on macOS Ventura - Safari & Brave (Chromium)
See vid here as posted on Discord: https://streamable.com/sd3huw

Resize the frmbuff if res size higher than 1080p? Albeit even if I switched my resolution to 1080p it didn't fix the problem, so it might be also a macOS related issue. Linux one I've posted above only happened at 4k, 2k worked fine.

**Comment by Its-Kenta** [comment]
Resolution at 2560x1440p -> We're getting a massive webrtc error log spam and instant disconnect from the server
https://streamable.com/qrpzis

**Comment by Its-Kenta** [comment]
<img width="3472" alt="Screenshot 2023-03-05 at 22 48 44" src="https://user-images.githubusercontent.com/106167071/222990451-64b68aa7-75a3-4063-8ea4-eede6d211cb2.png">

Framebuffer fixed
Can be closed? Ran at 4k resolution, unless you want to wait for Jomy to confirm if it works on his one too?

**Comment by unitoftime** [comment]
Nah we can close I think. Thanks for testing!
