### ISSUE TITLE
Text stops following player

### ISSUE THREAD

**Issue by Its-Kenta** [jstewart7/mmo#39]
Text speech will stop following the player if the texts in the textbox meets the box boundary

https://user-images.githubusercontent.com/106167071/222581050-68c5ce85-a798-4740-882d-cd678e9bc6f0.mp4

**Comment by unitoftime** [comment]
This looks to be caused by an optimization that I did in glitch where if the mesh is large enough I cache it once, only the problem is I don't correctly use the model matrix of the text mesh. So when the player moves, it updates the model matrix, but the cached mesh gets re-used with the old model matrix

**Comment by unitoftime** [comment]
Fixed here: https://github.com/unitoftime/glitch/commit/142873406cc4b6c8cdcfb7c1077a5927c6b9ffe2
